output "vpc_id" {
  description = "VPC ID"
  value       = aws_vpc.main.id
}

output "public_subnet_ids" {
  description = "Public subnet IDs"
  value       = aws_subnet.public[*].id
}

output "private_subnet_ids" {
  description = "Private subnet IDs"
  value       = aws_subnet.private[*].id
}

# RDS Outputs
output "rds_endpoint" {
  description = "RDS endpoint"
  value       = aws_db_instance.main.endpoint
}

output "rds_address" {
  description = "RDS address (hostname only)"
  value       = aws_db_instance.main.address
}

output "rds_port" {
  description = "RDS port"
  value       = aws_db_instance.main.port
}

output "rds_database_name" {
  description = "RDS database name"
  value       = aws_db_instance.main.db_name
}

# ECS Outputs
output "ecs_cluster_name" {
  description = "ECS cluster name"
  value       = aws_ecs_cluster.main.name
}

output "ecs_cluster_arn" {
  description = "ECS cluster ARN"
  value       = aws_ecs_cluster.main.arn
}

output "ecs_service_name" {
  description = "ECS service name"
  value       = aws_ecs_service.backend.name
}

output "ecr_repository_url" {
  description = "ECR repository URL"
  value       = aws_ecr_repository.backend.repository_url
}

# ALB Outputs
output "alb_dns_name" {
  description = "ALB DNS name"
  value       = aws_lb.main.dns_name
}

output "alb_zone_id" {
  description = "ALB zone ID (for Route 53)"
  value       = aws_lb.main.zone_id
}

output "alb_arn" {
  description = "ALB ARN"
  value       = aws_lb.main.arn
}

# S3 Outputs
output "s3_bucket_name" {
  description = "S3 bucket name"
  value       = aws_s3_bucket.main.id
}

output "s3_bucket_arn" {
  description = "S3 bucket ARN"
  value       = aws_s3_bucket.main.arn
}

# CloudWatch Outputs
output "cloudwatch_log_group" {
  description = "CloudWatch log group name"
  value       = aws_cloudwatch_log_group.ecs.name
}

output "sns_topic_arn" {
  description = "SNS topic ARN for alarms"
  value       = aws_sns_topic.alarms.arn
}

# Security Group Outputs
output "alb_security_group_id" {
  description = "ALB security group ID"
  value       = aws_security_group.alb.id
}

output "ecs_security_group_id" {
  description = "ECS security group ID"
  value       = aws_security_group.ecs.id
}

output "rds_security_group_id" {
  description = "RDS security group ID"
  value       = aws_security_group.rds.id
}

# ElastiCache Outputs
output "redis_primary_endpoint" {
  description = "ElastiCache Redis primary endpoint"
  value       = aws_elasticache_replication_group.main.primary_endpoint_address
}

output "redis_reader_endpoint" {
  description = "ElastiCache Redis reader endpoint"
  value       = aws_elasticache_replication_group.main.reader_endpoint_address
}

output "redis_port" {
  description = "ElastiCache Redis port"
  value       = aws_elasticache_replication_group.main.port
}

# Environment Variables for .env file
output "env_variables" {
  description = "Environment variables for .env file"
  value       = <<-EOT
# Generated by Terraform - Copy to .env.production

# AWS Core
AWS_REGION=${var.aws_region}
AWS_ACCOUNT_ID=${data.aws_caller_identity.current.account_id}

# RDS PostgreSQL
RDS_ENDPOINT=${aws_db_instance.main.endpoint}
RDS_ADDRESS=${aws_db_instance.main.address}
RDS_PORT=${aws_db_instance.main.port}
RDS_DATABASE=${aws_db_instance.main.db_name}
RDS_USERNAME=${var.db_username}
DATABASE_URL=postgresql://${var.db_username}:REPLACE_WITH_PASSWORD@${aws_db_instance.main.address}:${aws_db_instance.main.port}/${aws_db_instance.main.db_name}

# ElastiCache Redis
ELASTICACHE_ENDPOINT=${aws_elasticache_replication_group.main.primary_endpoint_address}
ELASTICACHE_READER_ENDPOINT=${aws_elasticache_replication_group.main.reader_endpoint_address}
ELASTICACHE_PORT=${aws_elasticache_replication_group.main.port}
REDIS_URL=redis://:REPLACE_WITH_AUTH_TOKEN@${aws_elasticache_replication_group.main.primary_endpoint_address}:${aws_elasticache_replication_group.main.port}

# S3
S3_BUCKET_NAME=${aws_s3_bucket.main.id}
S3_REGION=${var.aws_region}

# ECS
ECS_CLUSTER_NAME=${aws_ecs_cluster.main.name}
ECS_SERVICE_NAME=${aws_ecs_service.backend.name}
ECS_TASK_FAMILY=${aws_ecs_task_definition.backend.family}
ECR_REGISTRY=${data.aws_caller_identity.current.account_id}.dkr.ecr.${var.aws_region}.amazonaws.com
ECR_REPOSITORY=${aws_ecr_repository.backend.name}

# ALB
ALB_DNS_NAME=${aws_lb.main.dns_name}
ALB_TARGET_GROUP_ARN=${aws_lb_target_group.ecs.arn}

# CloudWatch
CLOUDWATCH_LOG_GROUP=${aws_cloudwatch_log_group.ecs.name}
CLOUDWATCH_METRICS_NAMESPACE=TriFlow/${title(var.environment)}

# SNS
SNS_TOPIC_ARN=${aws_sns_topic.alarms.arn}
EOT
  sensitive   = true
}
